services:
  login_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: login
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./login:/var/www/html
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./login:/var/www/html
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
